name: minor_release

on:
  push:
    tags:
    # Runs on any new tag
    # - 'v[0-9]+.[0-9]+.[0-9]+' # ignore release candidates otherwise the vX.0.0 check below would fail
    - 'v*'
  
env:
  DOCKER_REPOSITORY: osmolabs/osmosis
  CURRENT_TAG: ${{ github.ref_name }} # ref_name = the branch or tag name that triggered the workflow run.
 
jobs:

  create_artifacts:

    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      # - 
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - 
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - 
      #   name: Launch release process
      #   run: |
      #     make -f contrib/images/osmobuilder/Makefile release
      # - 
      #   name: Upload release folder
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: release
      #     path: release

  minor_release:
  
    runs-on: ubuntu-latest

    # Runs this workflow only on a minor release
    # A new major release would follow this pattern vX.0.0{-rcN}
    # if: ${{ !startsWith(github.ref_name, 'v*.0.0*') }}
    if: ${{ github.ref =~ 'v*.0.0*' }}

    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: test1
        run:  echo ${{ github.ref_name }}
      - 
        name: echo home
        run:  echo  $HOME
      - 
        name: pwd
        run:  pwd
      - 
        name: ls
        run:  ls
    
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - 
  #       name: Check out the repo
  #       uses: actions/checkout@v2
  #     - 
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     - 
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Docker meta
  #       id: meta
  #       uses: docker/metadata-action@v3
  #       with:
  #         images: ${{ env.DOCKER_REPOSITORY }}
  #         tags: |
  #           type=semver,pattern={{version}}
  #           type=semver,pattern={{major}}.{{minor}}
  #           type=semver,pattern={{major}}
  #     - 
  #       name: Build and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: Dockerfile
  #         context: .
  #         push: false
  #         platforms: linux/amd64
  #         tags: ${{ steps.meta.outputs.tags }}
  #     - 
  #       name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}